### ISSUE TITLE
程序不运行了

### ISSUE THREAD

**Issue by ioscoderlijie** [kobe1941/FFExtension#1]
项目中集成了FFExtension模块,有个按钮点击崩溃了,打不开响应得页面,是故意这样设计的吗?

**Comment by ioscoderlijie** [comment]
另外,项目中的极光推送一直报错,而第三方的源码是.a文件

**Comment by kobe1941** [comment]
具体出错的堆栈的日志？
如果是FFExtension捕捉到的崩溃，控制台会输出对应的一行log，你看看有没有
我没有加断言，所以即使捕捉到崩溃，APP也不会有问题的哈。
极光推送跟FFExtension没关系吧，我倒是发现高德SDK经常越界，但是也能正常运行

**Comment by ioscoderlijie** [comment]
ppDelegate.m:140	callStack:

[
	0   YuanPlus                          0x000000010325eb08 -[FFExceptionProxy reportExceptionWithMessage:extraDic:] + 212,
	1   YuanPlus                          0x0000000102b5cf94 -[NSData(FFExtension) ff_replaceBytesInRange:withBytes:] + 476,
	2   YuanPlus                          0x000000010347c3b8 -[JPUSHRequest packetData] + 884,
	3   YuanPlus                          0x0000000103482ca4 -[JPUSHSessionController doSendTcpRequest:] + 132,
	4   YuanPlus                          0x0000000103482bc0 -[JPUSHSessionController sendRequest:] + 136,
	5   YuanPlus                          0x0000000103442a70 -[JCOREClientController sendRequest:] + 80,
	6   YuanPlus                          0x000000010347c514 -[JPUSHRequest send] + 64,
	7   YuanPlus                          0x0000000103483d80 -[JPUSHSessionController doRegister] + 60,
	8   Foundation                          0x0000000181c185b8 __NSFireTimer + 88,
	9   CoreFoundation                      0x00000001811c2fc0 <redacted> + 28,
	10  CoreFoundation                      0x00000001811c2ce4 <redacted> + 864,
	11  CoreFoundation                      0x00000001811c24e4 <redacted> + 248,
	12  CoreFoundation                      0x00000001811c00cc <redacted> + 1928,
	13  CoreFoundation                      0x00000001810dfe58 CFRunLoopRunSpecific + 436,
	14  CoreFoundation                      0x000000018112ef54 CFRunLoopRun + 116,
	15  YuanPlus                                0x000000010346b3d4 -[JPUSHThread clientThreadMain] + 100,
	16  Foundation                             0x0000000181c170f4 <redacted> + 996,
	17  libsystem_pthread.dylib             0x0000000180e402b4 <redacted> + 308,
	18  libsystem_pthread.dylib             0x0000000180e40180 <redacted> + 0,
	19  libsystem_pthread.dylib             0x0000000180e3eb74 thread_start + 4
]

**Comment by ioscoderlijie** [comment]
这个是日志

**Comment by kobe1941** [comment]
这种就是数据越界了，Xcode的控制台会有实际的越界数据输出的
![image](https://user-images.githubusercontent.com/7099017/50394577-753f8a80-0799-11e9-8584-cc6b11d8690a.png)

**Comment by kobe1941** [comment]
你的问题是什么？
引入FFExtension后，你的APP崩溃在了你上面贴出的堆栈处？

**Comment by ioscoderlijie** [comment]
项目没崩溃,就是极光推送报错了,不影响运行

**Comment by kobe1941** [comment]
1.有个按钮点击崩溃了,打不开响应得页面。确定下这个跟FFExtension无关吧？
2.你可以把报错的信息在这里贴一下，不过我还是建议你把报错的信息发给极光推送，让他们去处理。
3.你试着注释上方的if判断条件，或者直接注释这个函数，看看还会不会有同样的报错信息？有的话，把控制台的详细log贴出来我看看

**Comment by ioscoderlijie** [comment]
1.排查了一下,第一个按钮点击崩溃了,跟FFExtension无关,是bugly上报崩溃信息后退出应用进程设置的是否
2.极光那边我已经反馈了,还没有给回复
3.直接注释函数后,不会包同样的信息,不过其他类也报类似的错了,都是关于越界的
![snip20181224_1](https://user-images.githubusercontent.com/15799619/50396487-62cb4e00-07a5-11e9-9b9a-f821120569c0.png)

**Comment by ioscoderlijie** [comment]
![snip20181224_2](https://user-images.githubusercontent.com/15799619/50396690-7b883380-07a6-11e9-936e-5485eb704908.png)

**Comment by kobe1941** [comment]
1.你这个是极光推送还是友盟？
2.集成FFExtension后是否会影响到APP的功能？
3.给个SDK的链接我试试看，不确定SDK内部有没有做越界保护

**Comment by kobe1941** [comment]
我的错，getBytes:length: 这个函数，系统的函数允许length越界，我明天多测试一下不同的系统看，如果都允许越界，这个函数就去掉。

**Comment by ioscoderlijie** [comment]
好的,我先把 //[NSData startHook];这个给注释了,再测测其他的
 if (option & FFHookOptionNSData) {
            //[NSData startHook];
        }

**Comment by kobe1941** [comment]
重新pod update即可 @ioscoderlijie
