### ISSUE TITLE
与jpush sdk 冲突

### ISSUE THREAD

**Issue by liulishuo** [kobe1941/FFExtension#2]
会导致jpush ，+ (void)registrationIDCompletionHandler:(void(^)(int resCode,NSString *registrationID))completionHandler 方法无回调，导致收不到推送消息。

**Comment by kobe1941** [comment]
如果控制台有错误log，贴一下错误信息？
另外贴一下你的初始化方式

**Comment by liulishuo** [comment]
0 0 VKProprietorAssistant 0x000000010493b0b4 -[FFExceptionProxy reportExceptionWithMessage:extraDic:] (FFExceptionProxy.m:0)
--
1 1 VKProprietorAssistant 0x0000000104940f48 -[NSData(FFExtension) ff_replaceBytesInRange:withBytes:] (NSData+FFExtension.m:190)
2 2 VKProprietorAssistant 0x0000000104c1d978 -[JPUSHRequest packetData] + 884
3 3 VKProprietorAssistant 0x0000000104c24264 -[JPUSHSessionController doSendTcpRequest:] + 132
4 4 VKProprietorAssistant 0x0000000104c24180 -[JPUSHSessionController sendRequest:] + 136
5 5 VKProprietorAssistant 0x0000000104be4930 -[JCOREClientController sendRequest:] + 80
6 6 VKProprietorAssistant 0x0000000104c1dad4 -[JPUSHRequest send] + 64
7 7 VKProprietorAssistant 0x0000000104c25340 -[JPUSHSessionController doRegister] + 60

**Comment by liulishuo** [comment]
FFExtension +[NSConcreteMutableData replaceBytesInRange:withBytes:], bytes is 0x1264348a0, range {24, 272} is out of bounds 0...293

-[FFExceptionProxy reportExceptionWithMessage:extraDic:] (FFExceptionProxy.m:0)
-[NSData(FFExtension) ff_replaceBytesInRange:withBytes:] (NSData+FFExtension.m:190)
-[JPUSHRequest packetData] + 884
-[JPUSHSessionController doSendTcpRequest:] + 132
-[JPUSHSessionController sendRequest:] + 136
-[JCOREClientController sendRequest:] + 80
-[JPUSHRequest send] + 64
-[JPUSHSessionController doRegister] + 60


++++++++初始化方式+++++++
 __weak typeof(self) weakSelf = self;	
    [[FFManager sharedInstance] startWorkWithOption:FFHookOptionAll unrecogziedSelectorClassPrefixs:@[] callBackBlock:^(NSDictionary *exceptionDic) {	
        [weakSelf reportExecptionToBugly:exceptionDic];	
    }];

**Comment by liulishuo** [comment]
[NSConcreteMutableData replaceBytesInRange:withBytes:] 此类问题非常多，上报非常频繁，不单单是jpush才会触发。

**Comment by liulishuo** [comment]
https://community.jiguang.cn/t/ios/28185
https://github.com/jasenhuang/NSObjectSafe/issues/16

**Comment by kobe1941** [comment]
@liulishuo 你好，测试发现你说的这个函数，不用对长度进行保护。但是bytes的空值保护是有必要的。
![image](https://user-images.githubusercontent.com/7099017/51657954-5bd06f00-1fe1-11e9-9a25-2045acfdf2df.png)
![image](https://user-images.githubusercontent.com/7099017/51657959-62f77d00-1fe1-11e9-817f-5b0ae7ac8722.png)

一会儿我去掉这个函数对长度的限制，感谢你的提醒~

**Comment by kobe1941** [comment]
更新版本到1.1.6即可
