### ISSUE TITLE
iOS 13

### ISSUE THREAD

**Issue by reacheung** [kobe1941/FFExtension#5]
请测试iOS13的兼容问题

**Comment by kobe1941** [comment]
有啥问题吗？有崩溃的话贴一下日志看看 @reacheung 
我还没升级。。

**Comment by lu520** [comment]
NSDictionary * dic = @{@"aa":@"111"};
NSDictionary * cc = [dic objectForKey:@"aa"];
NSDictionary * bb = [cc objectForKey:@"aaaaa"];
//报错信息
reason: '-[__NSCFConstantString objectForKey:]: unrecognized selector sent to instance 0x103045f98'
这种还是奔溃啊 从日志我们得到，对一个字符串使用了objectForKeye方式取值，编译器识别不了，抛出异常。

**Comment by kobe1941** [comment]
@lu520 认真阅读说明。。。
需要传类的字符串前缀，才会进行拦截
